### ISSUE TITLE
Could you please make a release?

### ISSUE THREAD

**Issue by yurivict** [dottedmag/x2x#26]
The source code says that the version is 1.30. But there is no release. Lack of releases can cause confusion, and the package not being updated because automatic release detectors will not find new versions.

**Comment by dottedmag** [comment]
See #21

**Comment by barak** [comment]
Since @dottedmag gave me write access (thanks, btw!) I'd be happy to step up and do release coordination. But truth is I barely use x2x anymore, so other people have to shake things down and test it and tell me "okay, hit the button, ready for a release!"

(Not that formal release numbers mean anything much nowadays, the Debian package just tracks the tip since it seems just as stable.)
