### ISSUE TITLE
x2x - error: can not open display

### ISSUE THREAD

**Issue by edgecate** [dottedmag/x2x#35]
I'm trying to connect from Ubuntu 18.04 to Mendel Linux but keep getting **x2x - error: can not open display**
Ubuntu 18.04 = 10.0.0.1
Mendel Linux = 10.0.0.2

Both Ubuntu and Mendel machines have enabled:
ForwardX11 in /etc/ssh/ssh_config, and 
X11Forwarding in /etc/ssh/sshd_config.

I've also executed **xhost +** on both machines.

I get the following outputs when I check DISPLAY:
Ubuntu 18.04:
`set | grep DISPLAY`
DISPLAY=:0

`echo $DISPLAY`
:0

Mendel:
`set | grep DISPLAY`
DISPLAY=:0
WAYLAND_DISPLAY=wayland-0

`echo $DISPLAY`
:0

So then I executed `export DISPLAY=:0` on both Ubuntu and Mendel.
And executed `export WAYLAND_DISPLAY=wayland-0` on Mendel.

And finally, from Ubuntu terminal, I execute:
`ssh -X mendel@10.0.0.2 x2x -from 10.0.0.1:0 -to 10.0.0.2:0 -west`
but get the following error:
`x2x - error: can not open display 10.0.0.1:0`

So then I tried:
`ssh -X mendel@10.0.0.2 x2x -from :0 -to 10.0.0.2:0 -west`
but get the following error:
`x2x - error: can not open display 10.0.0.2:0`

And then obviously:
`ssh -X mendel@10.0.0.2 x2x -from :0 -to :0 -west`
predictably gives:
`x2x: display names are both :0`

What else am I missing?

**Comment by barak** [comment]
What you need is one place (i.e., a single shell running on some machine) that has access to both X servers. Usually one will be in the `DISPLAY` environment variable, and the other you'll know. Let's say you have two machines, FOO and BAR, both on your desk, both running X servers. If you have a shell running on FOO, probably it will access the X server on FOO as `:0`, and the X server on BAR as `bar.local:0` or (if you've done `ssh -X FOO` from BAR) as `localhost:9` or something like that; that's because SSH is forwarding the X connection.

Without a little more information about your setup, it's hard to help. But it sounds like you don't care about security, so have no need for SSH etc.

Maybe try this.

On "mendel":
```
$ xlsclients -d :0 | head -2
$ xlsclients -d mendel:0 | head -2
$ xlsclients -d ubuntu:0 | head -2
```
On "ubuntu", exactly the same thing.

You may need to substitute resolvable names for the hosts above, like `mendel.local:0` or `mendel.lan:0` or even just use the raw IP address `10.0.0.2:0`.

Once you can access both servers from a single shell, you can invoke `x2x -to displayFOO -from displayBAR`

**Comment by edgecate** [comment]
Mate! You're a bloody legend! Really appreciate you taking time out of your day to help me out!!! :)

Got it kind of working (enough to test my use case).
I had to do it this way below because (I think) it uses the DISPLAY variable of "localhost:10" (or 9 or whatever) instead of just ":0" (without "localhost").

So using the same example again:
Ubuntu 18.04 = 10.0.0.1
Mendel Linux = 10.0.0.2

Starting from Ubuntu, I opened a terminal and SSHed into itself:
`ssh -X ubuntu_user@10.0.0.1`

Then inside Ubuntu-2, I SSHed into Mendel:
`ssh -X mendel_user@10.0.0.2`

Then SSHed back into Ubuntu with x2x:
`ssh -X ubuntu_user@10.0.0.1 x2x -from :0`
(It didn't work with -north/east/south/west)

A minature window in Mendel popped up and I could type characters from my Mendel keyboard to my Ubuntu screen.

However, when I use `ssh -X ubuntu_user@10.0.0.1 x2x **-to** :0` and the minature window pops up in Ubuntu, I can't get inside that minature window to type characters from my Ubuntu keyboard to Mendel display. And even if I expand the window my input still isn't registered.

But it was enough to test out a use case of mine which didn't end up working anyway (using the python keyboard module in Ubuntu using my Mendel keyboard using x2x).

Again, thanks for your help, barak!
