### ISSUE TITLE
Keyboard keys not being sent.

### ISSUE THREAD

**Issue by maca** [dottedmag/x2x#9]
Mouse pointer is working but type on the keyboard has no effect on remote machine, keyboard keys are not sent to my host machine though. Installed on a Raspberry Pi

**Comment by barak** [comment]
Would it make sense to make that patch? Or maybe add it as a command line option?

**Comment by djeis97** [comment]
I guess that depends where the actual issue is- x2x or the x server connection. Changing the decode from using the "from" x to using the "to" x has some important implications, I think. Might even actually be an extra feature to make that a command line option, but idk exactly how useful it would really be.

**Comment by traverseda** [comment]
Same problem here.

**Comment by alexoj** [comment]
I had this issue (mouse working, all keypresses logged as keycode 204) and got it to work by using `ssh -Y` instead of `ssh -X`.

**Comment by rhoit** [comment]
thanx @alexoj `-Y` worked for me!

**Comment by zerOnepal** [comment]
@rhoit thanks dai
![worked](https://cloud.githubusercontent.com/assets/1695906/15384730/67574080-1dbc-11e6-9910-8ce0c072371e.gif)

**Comment by oserin** [comment]
THY

**Comment by javanux** [comment]
worked for me too. Thanks @thapakazi :smile:

**Comment by eBug** [comment]
ssh -Y doesn't make a difference here. Letter keys work fine, but numbers are messed:
both 11 and 12 keycodes show as keycode 77 for example.

**Comment by bnaysakya** [comment]
worked for me too. Thanks @alexoj @thapakazi :bowing_man:

**Comment by vext01** [comment]
`-Y` worked here between a Linux and OpenBSD machine.

**Comment by Avamander** [comment]
`-Y` didn't work for me on Kubuntu->KFedora

**Comment by Avamander** [comment]
@barak 
> Would it make sense to make that patch? Or maybe add it as a command line option?

If it existed as a cli option it would theoretically give people the ability to try another fix before coming to issue tracker.

**Comment by dottedmag** [comment]
Unfortunately, there is not enough information to understand if this is a bug, a number of different bugs or a misconfiguration.

**Comment by Avamander** [comment]
What information is missing, I can probably test things out.

**Comment by dottedmag** [comment]
At least `xev` output from both machines.

However note that the project is dormant, so it will have to wait until a new maintainer steps in and solves the number of accumulated problems.

**Comment by progfou** [comment]
@Avamander, could it be because you are opening a Wayland session (default choice in Ubuntu, may be default in KUbuntu too) instead of an Xorg session?

Since a lot of people (including me) got this keyboard-only-problem “solved” with the ssh -Y option, it looks like it is just about a security control in the way of x2x (cf "man ssh", -Y option). The other case I know for x2x not working is when we use Wayland instead of Xorg. Both these cases are not bugs but only usage/configuration issues. So, IMHO, this bug report could be closed as “not a bug”, with comment from @alexoj set as a working solution.

**Comment by Avamander** [comment]
@progfou 
> Could it be because you are opening a Wayland session (default choice in Ubuntu, may be default in KUbuntu too) instead of an Xorg session?

No. KDE on Wayland is very experimental still.

I will investigate `ssh -Y`
